if (TARGET LZ4::LZ4)
  set(LZ4_FOUND TRUE)
  return ()
endif ()

if (LZ4_INCLUDE_DIR AND LZ4_LIBRARY)
  set(LZ4_FIND_QUIETLY TRUE)
endif ()

find_path(LZ4_INCLUDE_DIR
  NAMES lz4.h
  )

find_library(LZ4_LIBRARY
  NAMES lz4
  )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LZ4 DEFAULT_MSG LZ4_INCLUDE_DIR LZ4_LIBRARY)

mark_as_advanced(LZ4_INCLUDE_DIR LZ4_LIBRARY)

if (LZ4_FOUND)
  set(LZ4_INCLUDE_DIRS "${LZ4_INCLUDE_DIR}")
  set(LZ4_LIBRARIES "${LZ4_LIBRARY}")
endif()

if (LZ4_FOUND AND NOT TARGET LZ4::LZ4)
  add_library(LZ4::LZ4 INTERFACE IMPORTED)
  set_property(TARGET LZ4::LZ4 PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${LZ4_INCLUDE_DIR}")
  set_property(TARGET LZ4::LZ4 PROPERTY INTERFACE_LINK_LIBRARIES "${LZ4_LIBRARY}")
endif ()
