if (TARGET ZSTD::ZSTD)
  set(ZSTD_FOUND TRUE)
  return ()
endif ()

if (ZSTD_INCLUDE_DIR AND ZSTD_LIBRARY)
  set(ZSTD_FIND_QUIETLY TRUE)
endif ()

find_path(ZSTD_INCLUDE_DIR
  NAMES zstd.h
  )

find_library(ZSTD_LIBRARY
  NAMES zstd
  )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZSTD DEFAULT_MSG ZSTD_INCLUDE_DIR ZSTD_LIBRARY)

mark_as_advanced(ZSTD_INCLUDE_DIR ZSTD_LIBRARY)

if (ZSTD_FOUND)
  set(ZSTD_INCLUDE_DIRS "${ZSTD_INCLUDE_DIR}")
  set(ZSTD_LIBRARIES "${ZSTD_LIBRARY}")
endif()

if (ZSTD_FOUND AND NOT TARGET ZSTD::ZSTD)
  add_library(ZSTD::ZSTD INTERFACE IMPORTED)
  set_property(TARGET ZSTD::ZSTD PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${ZSTD_INCLUDE_DIR}")
  set_property(TARGET ZSTD::ZSTD PROPERTY INTERFACE_LINK_LIBRARIES "${ZSTD_LIBRARY}")
endif ()
