if (TARGET LZO::LZO)
  set(LZO_FOUND TRUE)
  return ()
endif ()

if (LZO_INCLUDE_DIR AND LZO_LIBRARY)
  set(LZO_FIND_QUIETLY TRUE)
endif ()

find_path(LZO_INCLUDE_DIR
  NAMES lzo/lzoconf.h
  )

find_library(LZO_LIBRARY
  NAMES lzo2
  )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LZO DEFAULT_MSG LZO_INCLUDE_DIR LZO_LIBRARY)

mark_as_advanced(LZO_INCLUDE_DIR LZO_LIBRARY)

if (LZO_FOUND)
  set(LZO_INCLUDE_DIRS "${LZO_INCLUDE_DIR}")
  set(LZO_LIBRARIES "${LZO_LIBRARY}")
endif()

if (LZO_FOUND AND NOT TARGET LZO::LZO)
  add_library(LZO::LZO INTERFACE IMPORTED)
  set_property(TARGET LZO::LZO PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${LZO_INCLUDE_DIR}")
  set_property(TARGET LZO::LZO PROPERTY INTERFACE_LINK_LIBRARIES "${LZO_LIBRARY}")
endif ()
